title: TaskReminderForStasy
description: A simple task reminder app for my Russian Client named Stasy.
google_analytics: 
show_downloads: false
theme: jekyll-theme-architect

gems:
  - jekyll-mentions
