title: TaskReminder App
description: A simple task reminder app for Anstasia  Domanskya ( Stasy),Minsk, Belarus.
google_analytics: 
show_downloads: false
theme: jekyll-theme-architect

gems:
  - jekyll-mentions
